EYYY this is my pull request
jeremyparadie/CASPER pull request #10
Opened 2020-02-14 22:12 UTC by idetore

To whom it may concern, 

This is my pull request. Thanks!

Best,
Ian

2020-02-14 22:30 UTC, TG-Techie commented
Ian, please describe what changes you made to the branch in the above comment

2020-02-16 05:05 UTC, JeremyParadie requested changes
please fix the encoding issue with the double quotes and the reformatting of the parse function in robot.ino

2020-02-16 05:05 UTC, JeremyParadie commented on firmware/robot/GPSWrapper.cpp
> +String GPSWrapper::getTime(){                   //returns the time in â€œHH:MM:SS.SSS UTCâ€� Time is UTC, not timezone or daylight saving offset.
```suggestion
String GPSWrapper::getTime(){                   //returns the time in "HH:MM:SS.SSS UTC" Time is UTC, not timezone or daylight saving offset.
```

2020-02-16 05:05 UTC, JeremyParadie commented on firmware/robot/GPSWrapper.cpp
> +String GPSWrapper::getDate(){                   //returns date in â€œYYYY-MM-DDâ€� format
```suggestion
String GPSWrapper::getDate(){                   //returns date in "YYYY-MM-DD" format
```

2020-02-16 05:05 UTC, JeremyParadie commented on firmware/robot/GPSWrapper.cpp
> +  return String("20")+String(GPS.year)+String("-")+String(GPS.month)+String("-")+String(GPS.day); //return date in â€œYYYY-MM-DDâ€� format
```suggestion
  return String("20")+String(GPS.year)+String("-")+String(GPS.month)+String("-")+String(GPS.day); //return date in "YYYY-MM-DD" format
```

2020-02-16 05:05 UTC, JeremyParadie commented on firmware/robot/GPSWrapper.h
> +    String getTime();                 //Returns the time in â€œHH:MM:SS.SSS UTCâ€� Time is UTC, not timezone or daylight saving offset.
```suggestion
    String getTime();                 //Returns the time in "HH:MM:SS.SSS UTC" Time is UTC, not timezone or daylight saving offset.
```

2020-02-16 05:05 UTC, JeremyParadie commented on firmware/robot/GPSWrapper.h
> +    String getTime();                 //Returns the time in â€œHH:MM:SS.SSS UTCâ€� Time is UTC, not timezone or daylight saving offset.
```suggestion
    String getTime();                 //Returns the time in "HH:MM:SS.SSS UTC" Time is UTC, not timezone or daylight saving offset.
```

2020-02-16 05:05 UTC, JeremyParadie commented on firmware/robot/GPSWrapper.h
> +    String getDate();                 //Returns date in â€œYYYY-MM-DDâ€� format
```suggestion
    String getDate();                 //Returns date in "YYYY-MM-DD" format
```

2020-02-16 05:06 UTC, closed without merging